@startuml C4_Component_Diagram_GRA

!include ../libs/c4/C4_Component.puml

skinparam defaultTextAlignment center
skinparam nodesep 50
skinparam ranksep 60

title Diagrama de Componentes - Módulo GRA: Gestión Pagos y Finanzas

ContainerDb(database, "Base de Datos", "MySQL", "Almacena los detalles de los pagos realizados por alicuota, por multas, por mora y por gastos")
System_Ext(payment_sys, "Sistema de Gestión de Pagos", "Procesa pagos con tarjeta y transferencias.")
' TODO: Procesa o Registra, actualizar casos de uso específicos para cada tipo de pago.

Container(grf_module, "Módulo GRF", "Java Module", "Gestiona el envío de notificaciones\ny comunicados a residentes y personal.")
Container(grc_module, "Módulo GRC", "Java Module", "Administra el catálogo detallado y los registros de propiedad de todas las unidades y áreas comunes del condominio.")
Container(grd_module, "Módulo GRD", "Java Module", "Permite visualizar la disponibilidad, agendar, cancelar de forma autónoma las reservas de las áreas comunes del condominio y agregar observaciones.")

Container_Boundary(desktop_app, "Aplicación de Escritorio - Módulo GRA") {

    ' ── Vistas ─────────────────────────
    Component(vista_pagos, "Vista de Registro de Pagos", "JavaFX", "Interfaz para registrar y modificar pagos de alícuota, multas y reservas.")
    Component(vista_deuda, "Vista de Registro de Deudas", "JavaFX", "Interfaz para registrar y modificar deudas de alícuota, multas y reservas.")
    ' Component(vista_gastos, "Vista de Registro de Gastos", "JavaFX", "Interfaz para registrar gastos comunes y extraordinarios.")
    ' TODO: Especificar que los gastos se registran a través de solicitudes, y que el controlador de solicitudes se encarga de registrar los gastos aprobados.

    Component(vista_reportes, "Vista de Reportes Generales", "JavaFX", "Interfaz para generar reportes de pagos, y gastos.")
    Component(vista_parametros, "Vista de Parámetros", "JavaFX", "Interfaz para definir valores de alicuota y entidades bancarias.")
    Component(vista_solicitudes, "Vista de Solicitudes", "JavaFX", "Interfaz para realizar y aceptar solicitudes referentes a los pagos.")
    Component(vista_personal, "Vista de Reportes Personales", "JavaFX", "Interfaz para generar reportes de pagos.")

    ' ── Controladores ─────────────────────────
    Component(ctrl_pagos, "Controlador de Registro de Pagos", "Java Controller", "Recibe las acciones de la interfaz y registra, modifica o notifica pagos de alícuota, multas y reservas.")
    ' TODO: Controlador que modifica, además de eliminar forma de pago recurrente.???

    Component(ctrl_deudas, "Controlador de Registro de Deudas", "Java Controller", "Recibe las acciones de la interfaz y registra, modifica o notifica deudas de alícuota, multas y reservas.")
    ' Component(ctrl_gastos, "Controlador de Registro de Gastos", "Java Controller", "Recibe las acciones de la interfaz y registra gastos comunes y extraordinarios.")
    Component(ctrl_reportes, "Controlador de Reportes Generales", "Java Controller", "Recibe las acciones de la interfaz y genera reportes de pagos, y gastos.")
    Component(ctrl_parametros, "Controlador de Parámetros", "Java Controller", "Recibe las acciones de la interfaz y define valores de alicuota y entidad bancaria.")
    Component(ctrl_solicitudes, "Controlador de Solicitudes", "Java Controller", "Recibe las acciones de la interfaz y realiza o acepta solicitudes referentes a los pagos.")
    Component(ctrl_personal, "Controlador de Reportes Personales", "Java Controller", "Recibe las acciones de la interfaz y genera reportes de pagos.")

    ' ── Modelo ────────────────────
    Component(model_pagos, "Servicio de Registro de Pagos", "Java Service", "Registra y modifica los pagos y deudas.")
    ' Component(model_gastos, "Servicio de Registro de Gastos", "Java Service", "Registra gastos y su detalle.")
    Component(model_reportes_gastos, "Servicio de Reportes de Gastos", "Java Service", "Genera reportes financieros.")
    Component(model_reportes_pagos, "Servicio de Reportes de Pagos", "Java Service", "Genera reportes de pagos y deudas.")
    Component(model_parametros, "Servicio de Parámetros", "Java Service", "Difine valores de alicuota y entidades bancarias.")
    Component(model_solicitudes, "Servicio de Solicitudes", "Java Service", "Procesa solicitudes referentes a los pagos.")

}

 ' Conexión vista-controladores
Rel(vista_pagos, ctrl_pagos, "Envia Solicitudes de Registro de Pagos")
Rel(vista_deuda, ctrl_deudas, "Envia Solicitudes de Registro de Deudas")
' Rel(vista_gastos, ctrl_gastos, "Envia Solicitudes de Registro de Gastos
Rel(vista_reportes, ctrl_reportes, "Envia soliicitud de generación de reportes generales")
Rel(vista_parametros, ctrl_parametros, "Envia solicitudes de actualización de parámetros")
Rel(vista_solicitudes, ctrl_solicitudes, "Envia solicitudes de gestión de solicitudes")
Rel(vista_personal, ctrl_personal, "Envia solicitud de generación de reportes personales")

' Conexión controladores-modelo
Rel(ctrl_pagos, model_pagos, "Registrar pagos.")
' Rel(ctrl_gastos, model_gastos, "Registrar gasto")
Rel(ctrl_reportes, model_reportes_gastos, "Generar reporte de gastos.")
Rel(ctrl_reportes, model_reportes_pagos, "Generar reporte de pagos.")
Rel(ctrl_parametros, model_parametros, "Actualizar parámetros.")
Rel(ctrl_solicitudes, model_solicitudes, "Gestionar solicitudes.")
Rel(ctrl_personal, model_reportes_pagos, "Generar reportes personales.")
Rel(ctrl_deudas, model_pagos, "Registrar deudas.")

' Conexión modelo con otros módulos y servicios externos
Rel(model_pagos, payment_sys, "Procesa pagos", "API REST")
Rel(grd_module, model_pagos, "Registra multas por observaciones  en espacios comunes", "API REST")
Rel(model_pagos, grc_module, "Calcular alicuota", "API REST")
Rel(model_pagos, grf_module, "Notificar deudas y pagos", "API REST")
Rel(model_solicitudes, model_pagos, "Generar pago en cuotas", "API REST")


' Conexión con la base de datos
Rel(model_pagos, database, "Lee/Escribe", "JDBC/SQL")
Rel(model_reportes_pagos, database, "Lee/Escribe", "JDBC/SQL")
Rel(model_parametros, database, "Lee/Escribe", "JDBC/SQL")
Rel(model_reportes_gastos, database, "Lee/Escribe", "JDBC/SQL")

@enduml
